
SUBJECTNAMES = ("Python Programming", "Calculus", "Physics")


MAXMARKPERSUBJECT = 100.0


TOTALMAXMARKS = len(SUBJECTNAMES) * MAXMARKPERSUBJECT

MINATTENDANCEPERCENTAGE = 75.0

VALIDGRADES = frozenset({"A", "B", "C", "D", "F"})

FLAGACTIVE = 1 << 0

FLAGFEEPAID = 1 << 1

FLAGSCHOLARSHIP = 1 << 2
